title: Paula Bailey # your name (or website title) here
logo: "/images/100_0061.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
Highly self-motivated, goal-oriented professional, and aspring Data Scientist committed to pursuing a career in data analytics, data science, or data engineering. At this step in my journey, I am pursuing a second undergraduate degree at University of NC at Charlotte in Data Science with a graduation date of May 2025. Ultimately, I am seeking an opportunity in the greater Charlotte or surrounding areas to apply the academic skill set I have gained along with real-world work experience as a business professional. 
  <br><br>
2024 is the year of meeting new people, expanding my knowledge, and sharing the knowledge I have learned. 
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/paulabailey21/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
