title: Paula Bailey # your name (or website title) here
logo: "/images/100_0061.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Highly self-motivated and goal-oriented professional who is passionate about harnessing the power of data to drive impactful decisions.  I have a strong foundation in data analysis, cloud computing, and database management. I have a proven track record of conducting comprehensive data reconciliations, performing plan valuations, and collaborating with cross-functional teams to deliver projects on time and within budget. 
  <br><br>

  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/paulabailey21/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
